[phases.setup]
nixPkgs = ["jdk21_headless"]

[phases.build]
cmds = [
  "chmod +x bot/gradlew",
  "cd bot && ./gradlew clean build --no-daemon -x test"
]

[start]
cmd = "java -jar bot/build/libs/bot-1.0.0.jar"
